#!/usr/bin/perl -w

# 生成 usys.S；其中每个桩函数都是用户程序进入对应系统调用的接口。

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n"; # 把系统调用编号写入 a7 寄存器。
    print " ecall\n"; # 生成 ecall 指令，使 CPU 从用户态陷入内核态。
    print " ret\n"; # 内核返回用户态后，桩函数再按普通函数约定返回。
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("mmap");
entry("munmap");
