#!/usr/bin/perl -w

# 生成 usys.S 汇编文件，其中每个桩函数都是用户程序进入对应系统调用的接口。

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n"; # 把系统调用编号放入a7寄存器
    print " ecall\n"; # 在这里生成的这句汇编指令，让 CPU 从用户态陷入内核态
    print " ret\n"; # 用户函数的普通函数返回指令，等内核处理完并返回用户态
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("trace");
entry("sysinfo");


